Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
ashish 123 ashih234
Traceback (most recent call last):
  File "C:\Users\Ashish Umrao\Documents\infoysis\e.py", line 14, in <module>
    Print(func(l1))
NameError: name 'Print' is not defined
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
ashis 123 ashis34
Traceback (most recent call last):
  File "C:\Users\Ashish Umrao\Documents\infoysis\e.py", line 14, in <module>
    print(func(l1))
NameError: name 'func' is not defined
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
aass 344 as12
Traceback (most recent call last):
  File "C:\Users\Ashish Umrao\Documents\infoysis\e.py", line 14, in <module>
    print(func1(l1))
  File "C:\Users\Ashish Umrao\Documents\infoysis\e.py", line 7, in func1
    for I in range(Len(l1)):
NameError: name 'Len' is not defined
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
ass 44
Traceback (most recent call last):
  File "C:\Users\Ashish Umrao\Documents\infoysis\e.py", line 14, in <module>
    print(func1(l1))
  File "C:\Users\Ashish Umrao\Documents\infoysis\e.py", line 7, in func1
    for I in range(Len(l1)):
NameError: name 'Len' is not defined
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
aa 22
Traceback (most recent call last):
  File "C:\Users\Ashish Umrao\Documents\infoysis\e.py", line 14, in <module>
    print(func1(l1))
  File "C:\Users\Ashish Umrao\Documents\infoysis\e.py", line 12, in func1
    Lt.append(v)
NameError: name 'v' is not defined
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
qwww
[0, 4]
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
asss 44444
[0, 4]
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
233
[3, 0]
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
3 33 555 assss
[1, 0]
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
ddddd
['ddddd']
Traceback (most recent call last):
  File "C:\Users\Ashish Umrao\Documents\infoysis\e.py", line 19, in <module>
    print(func1(l1))
  File "C:\Users\Ashish Umrao\Documents\infoysis\e.py", line 15, in func1
    v1 +=len(l1[I])
UnboundLocalError: local variable 'v1' referenced before assignment
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
assss 233
['assss', '233']
[0, 5]
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
ashihs 123
None
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
aassss
True
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
as 33
[]
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
4444 ffff
[4, 4]
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
ashish 4444
[4, 6]
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
1,1,2,3,1
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
1,1,2,3,1
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
1,2,3
['1', '2', '3']
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1,1,2,3,3]
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1,2,3]
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1,2,34]
[1,2,34]
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1,2,3,4]
[1,2,3,4]
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1,2,3,4]
False
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1,2,3,4]
False
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1,2,3,4]
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1,2,3,4]
Traceback (most recent call last):
  File "C:/Users/Ashish Umrao/Documents/infoysis/problem6.py", line 15, in <module>
    print(py(lt))
  File "C:/Users/Ashish Umrao/Documents/infoysis/problem6.py", line 12, in py
    print(l[i],l[i+1],l[i+1])
NameError: name 'l' is not defined
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1,2,3,4]
[ 1 1
1 , ,
, 2 2
2 , ,
, 3 3
3 , ,
, 4 4
4 ] ]
Traceback (most recent call last):
  File "C:/Users/Ashish Umrao/Documents/infoysis/problem6.py", line 15, in <module>
    print(py(lt))
  File "C:/Users/Ashish Umrao/Documents/infoysis/problem6.py", line 12, in py
    print(lt[i],lt[i+1],lt[i+1])
IndexError: string index out of range
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1,2,3,4]
[ 1 1
1 , ,
, 2 2
2 , ,
, 3 3
3 , ,
, 4 4
4 ] ]
Traceback (most recent call last):
  File "C:/Users/Ashish Umrao/Documents/infoysis/problem6.py", line 17, in <module>
    print(py(lt))
  File "C:/Users/Ashish Umrao/Documents/infoysis/problem6.py", line 13, in py
    lt[i+1],
IndexError: string index out of range
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1,2,3,4]
[
1
,
2
,
3
,
4
]
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1,2,3,4]
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1, 1, 2, 3, 1]
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1, 1, 2, 3, 1]
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1, 1, 2, 3, 1]
0
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1, 1, 2, 3, 1]
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1, 1, 2, 3, 1]
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1, 1, 2, 3, 1]
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1, 1, 2, 3, 1]
None
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======

======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1, 1, 2, 3, 1]
False
>>> 
======= RESTART: C:/Users/Ashish Umrao/Documents/infoysis/problem6.py =======
[1,2,3]
False
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
['123']
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
['123']
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
['1', '2', '3']
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
738
Traceback (most recent call last):
  File "C:/Users/Ashish Umrao/Documents/infoysis/aa.py", line 14, in <module>
    for i in range(len(n)-len(n-1)):
TypeError: unsupported operand type(s) for -: 'list' and 'int'
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
738
Traceback (most recent call last):
  File "C:/Users/Ashish Umrao/Documents/infoysis/aa.py", line 14, in <module>
    for i in range(len(n1)):
TypeError: object of type 'int' has no len()
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
735
Traceback (most recent call last):
  File "C:/Users/Ashish Umrao/Documents/infoysis/aa.py", line 15, in <module>
    if( n1*int(n([i])*int(n[i+1])*int(n[i+2])))==m:
TypeError: 'list' object is not callable
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
738
Traceback (most recent call last):
  File "C:/Users/Ashish Umrao/Documents/infoysis/aa.py", line 16, in <module>
    count +=n1*n[i]
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
738
Traceback (most recent call last):
  File "C:/Users/Ashish Umrao/Documents/infoysis/aa.py", line 16, in <module>
    count +=n1*int(n[i],base=10)
IndexError: list index out of range
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
738
Traceback (most recent call last):
  File "C:/Users/Ashish Umrao/Documents/infoysis/aa.py", line 16, in <module>
    count +=n1*int(n[i])
IndexError: list index out of range
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
738
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
738
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
738
123
369
738
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
738
123
369
738
it is a seed of second no
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
45
1000
its not seed of second no
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
738
Traceback (most recent call last):
  File "C:/Users/Ashish Umrao/Documents/infoysis/aa.py", line 12, in <module>
    n1=int(n)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
738
123 ['1', '2', '3'] 738
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
738
Traceback (most recent call last):
  File "C:/Users/Ashish Umrao/Documents/infoysis/aa.py", line 23, in <module>
    print(py(n1,n,m))
  File "C:/Users/Ashish Umrao/Documents/infoysis/aa.py", line 18, in py
    count +=n1*int(n[i])
UnboundLocalError: local variable 'count' referenced before assignment
>>> 
========== RESTART: C:/Users/Ashish Umrao/Documents/infoysis/aa.py ==========
123
738
it is a seed of second no
>>> 
=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========

=========== RESTART: C:\Users\Ashish Umrao\Documents\infoysis\e.py ===========
{'D':300,'D':200,'W':200,'D':100}
